# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.5.1

RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.1.zip
#RUN /usr/share/kibana/bin/kibana-plugin install x-pack
