# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.1

#ENV ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack

#CMD ["-E", "network.host=0.0.0.0", "-E", "discovery.zen.minimum_master_nodes=1"]
